# Generated by Django 5.0.1 on 2024-02-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_created']},
        ),
    ]
